### ISSUE TITLE
Compilation Error on OF 2.3.x - 2.4.x

### ISSUE THREAD

**Issue by WeatherMan5** [maHein/curleAnalogy#1]
HI maHein,
thanks for the upload, really interesting.
I have compiled successfully for OF3.0.x but I am now struggling to have it working on an older version of OF (2.3.x-2.4.x)

Do you have a port of the library for these version?

Many Thanks
Ste

**Comment by maHein** [comment]
Hello Ste,

thanks for you interest in my little project.

I don't have an older version right away. Unfortunately, I am quite busy with my PhD thesis at the moment. Nevertheless, I will try to upload an older version next week.

Kind regards
Martin

**Comment by maHein** [comment]
Hello Ste,

I compiled the library without any problems using OpenFOAM 2.3.x and 2.4.x. Can you post your compilation errors?

Martin

**Comment by WeatherMan5** [comment]
Hi Martin,
this is the error I am getting:
Curle/Curle.C: In member function ‘virtual void Foam::Curle::writeFileHeader(Foam::label)’:
Curle/Curle.C:62:54: error: ‘writeHeader’ was not declared in this scope
         writeHeader(file(i), "Curle Acoustic Analogy");
                                                      ^
Curle/Curle.C:63:39: error: ‘writeCommented’ was not declared in this scope
         writeCommented(file(i), "Time");
                                       ^
Curle/Curle.C: In member function ‘void Foam::Curle::writeCurle()’:
Curle/Curle.C:95:52: error: ‘setw’ was not declared in this scope
     file(0) << obr_.time().value() << tab << setw(1) << "   ";
                                                    ^
Curle/Curle.dep:514: recipe for target 'Make/linux64GccDPOpt/Curle.o' failed
make: *** [Make/linux64GccDPOpt/Curle.o] Error 1

I am running a "tweaked" version of OF 2.4 so I should probably try to compile it in a clean 2.4.x version

Ste

**Comment by WeatherMan5** [comment]
Hi Martin,
I finally had some time to look into this issue again
Did you change something in the source code to compile it in the legacy versions of OF?

In the source code for OF-dev I can see:
#include "regionFunctionObject.H"
#include "logFiles.H"

while in the one for 4.x:
#include "writeFiles.H"

Unfortunately I cannot see these files in either OF 2.3.x  or OF 2.4.x

Thanks
Ste

**Comment by maHein** [comment]
Hi,

the OpenFOAM changed the source code a few times during the versions 2.4.x to 4.x for function objects. I uploaded a new version of the Curle Analogy for OpenFOAM 2.4.x on github.

Feel free to use it.

Regards

Martin

Dipl.-Ing. Martin Heinrich
Institut für Mechanik und Fluiddynamik
TU Bergakademie Freiberg
Lampadiusstr. 4
D-09596 Freiberg

Tel.: +49 – (0)3731 – 39 3053
Fax.: +49 – (0)3731 – 39 3455

E-mail: martin.heinrich@imfd.tu-freiberg.de

Von: WeatherMan5 [mailto:notifications@github.com]
Gesendet: Wednesday, November 02, 2016 4:51 PM
An: maHein/acousticAnalogy
Cc: Heinrich Martin; State change
Betreff: Re: [maHein/acousticAnalogy] Compilation Error on OF 2.3.x - 2.4.x (#1)


Hi Martin,
I finally had some time to look into this issue again
Did you change something in the source code to compile it in the legacy versions of OF?

In the source code for OF-dev I can see:
#include "regionFunctionObject.H"
#include "logFiles.H"

while in the one for 4.x:
#include "writeFiles.H"

Unfortunately I cannot see these files in either OF 2.3.x or OF 2.4.x

Thanks
Ste

**Comment by WeatherMan5** [comment]
That's great!
I will give it a shot and let you know!

Many Thanks
Ste

**Comment by WeatherMan5** [comment]
Hi Martin, 
I have managed to compile it under 2.4 and seems to be runnig fine

Many Thanks

A side note, is the plot in the validation section showing PSD or SPL? 
I had a quick look at the paper cited and had to scale the PSD data presented there to match your plot so I would assume is actually in SPL

Unfortunately the test case is too big for my machine otherwise I would have tried it directly myself 

Thanks
Ste

**Comment by maHein** [comment]
Hello Ste,

I am glad the library is working for you!

Yes, it should be SPL.

Kind Regards,

Martin

On 15 Nov 2016, at 20:55, WeatherMan5 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Martin,
I have managed to compile it under 2.4 and seems to be runnig fine

Many Thanks

A side note, is the plot in the validation section showing PSD or SPL?
I had a quick look at the paper cited and had to scale the PSD data presented there to match your plot so I would assume is actually in SPL

Unfortunately the test case is too big for my machine otherwise I would have tried it directly myself

Thanks
Ste
